/*
 * usart_user.c
 *
 *  Created on: Oct 8, 2023
 *      Author: oscar
 */

#include "usart_user.h"

void USART1_Init(void) {
	RCC->APB2ENR |= (RCC_APB2ENR_USART1EN);
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN);

	// GPIO Settings
	// TX PA9
	GPIOA->MODER &= ~(GPIO_MODER_MODER9_0);
	GPIOA->MODER |= (GPIO_MODER_MODER9_1);

	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT9);

	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR9_0);
	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR9_1);

	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL9_0);
	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL9_1);
	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL9_2);
	GPIOA->AFR[1] &= ~(GPIO_AFRH_AFSEL9_3);

	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR9_0);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR9_1);

	// RX PA10
	GPIOA->MODER &= ~(GPIO_MODER_MODER10_0);
	GPIOA->MODER |= (GPIO_MODER_MODER10_1);

	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT10);

	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR10_0);
	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR10_1);

	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL10_0);
	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL10_1);
	GPIOA->AFR[1] |= (GPIO_AFRH_AFSEL10_2);
	GPIOA->AFR[1] &= ~(GPIO_AFRH_AFSEL10_3);

	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR10_0);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR10_1);

	// USART1
	USART1->CR1 &= ~(USART_CR1_UE);
	USART1->CR1 |= (USART_CR1_UE);
	USART1->CR1 &= ~(USART_CR1_M); // 8 bits
	USART1->BRR = 0x2D9; // 115200
	USART1->CR1 |= (USART_CR1_TE);
	USART1->CR1 |= (USART_CR1_RE);
	// DMA
	USART1->CR3 |= (USART_CR3_DMAT);
}
